export interface IRegistro{
  id?: number,
  nome: string,
  quantidade: number,
  dataRetirada: string,
  unidadeMedida?: string,
  contador?: number,
  datasAcumuladas?: any,
  quantidadeAcumuladas?: any,
  quantidadeDatas?: any,
  mediaDiaria?: any,
  periodoMaximo?: any,
  retencao?: any,
  quantidadeMaximaEstoque?: any,
  quantidadeMinimaEstoque?: any,
  quantidadeParaComprar?: any,
  sugerir?: boolean,
}